# Generated by Django 4.1.7 on 2023-03-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_fertilizersmodel_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registertable',
            name='aggreid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registertable',
            name='farmerid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
