# Generated by Django 4.1.7 on 2023-03-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_orderstable_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstable',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Pending', max_length=20, null=True),
        ),
    ]
